# Generated by Django 4.2.16 on 2024-11-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_services_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
