# Generated by Django 4.2.16 on 2024-11-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='phone',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
