# Generated by Django 4.2.16 on 2024-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_contactprofile_user_contactprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
