# Generated by Django 4.2.16 on 2024-11-05 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_product_options_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['puplish_date']},
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='category',
            name='puplish_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
