# Generated by Django 4.2.16 on 2024-11-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_searchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
